
-- Department data
INSERT ALL
    INTO C_DEPARTMENT VALUES('Research', 5, '333445555', TO_DATE('1988-05-22', 'YYYY-MM-DD'))

    INTO C_DEPARTMENT VALUES('Administration', 4, '987654321', TO_DATE('1995-01-01', 'YYYY-MM-DD'))

    INTO C_DEPARTMENT VALUES('Headquarters', 1, '888665555', TO_DATE('1981-06-19', 'YYYY-MM-DD'))
SELECT 1 
FROM DUAL;


ALTER TABLE C_DEPARTMENT
MODIFY DNAME VARCHAR(20);  

SELECT * FROM C_DEPARTMENT;

DESC C_DEPARTMENT;

-- employees' dept no update
UPDATE C_EMPLOYEE
SET DNO = 5
WHERE FNAME IN ('John', 'Franklin', 'Ramesh', 'Joyce');

UPDATE C_EMPLOYEE
SET DNO = 4
WHERE FNAME IN ('Alicia', 'Jennifer', 'Ahmad');

UPDATE C_EMPLOYEE
SET DNO = 1
WHERE FNAME = 'James';

