-- OPTIONAL CONSTRAINT <NAME>
-- ON UPDATE CASCADE NOT ALLOWED, UNIQUE NOT ALLOWED WITH PK 

--EMPLOYEE


CREATE TABLE C_EMPLOYEE(
    SSN VARCHAR(9) CONSTRAINT SSN_PK PRIMARY KEY,
    FNAME VARCHAR(15) NOT NULL,
    MINIT VARCHAR(1) NOT NULL,
    LNAME VARCHAR(15) NOT NULL,
    ADDRESS VARCHAR(50),
    SEX VARCHAR(1) NOT NULL,
    SALARY INTEGER 
        CONSTRAINT SALARY_CHK CHECK (SALARY > 0)
);

DESC C_EMPLOYEE;


-- superssn

ALTER TABLE C_EMPLOYEE
ADD SUPER_SSN VARCHAR(9)
CONSTRAINT SUPER_SSN_FK REFERENCES C_EMPLOYEE(SSN);

-- FORGOT BDATE
ALTER TABLE C_EMPLOYEE
ADD BDATE DATE NOT NULL;


-- RESET
DROP TABLE C_EMPLOYEE;

-- TODO : dno 


-- DEPARTMENT

CREATE TABLE C_DEPARTMENT(
    DNAME VARCHAR(20) NOT NULL,
    DNUMBER INTEGER,
    MGR_SSN VARCHAR(9),
    MGR_START_DATE DATE,
    CONSTRAINT DNAME_CK UNIQUE(DNAME),
    CONSTRAINT DEPT_PK PRIMARY KEY(DNUMBER),
    CONSTRAINT MGR_FK FOREIGN KEY(MGR_SSN) REFERENCES C_EMPLOYEE(SSN)
);

-- DNO IN EMP

ALTER TABLE C_EMPLOYEE
ADD DNO INTEGER
CONSTRAINT DNO_FK 
    REFERENCES C_DEPARTMENT(DNUMBER) ON DELETE CASCADE;

-- RESET 
DROP TABLE C_DEPARTMENT;

-- DEPT_LOCATIONS
CREATE TABLE DEPT_LOCATIONS(
    DNUMBER INTEGER,
    DLOCATION VARCHAR(20),

    CONSTRAINT LOC_FK FOREIGN KEY(DNUMBER) REFERENCES C_DEPARTMENT(DNUMBER) ON DELETE CASCADE,
    CONSTRAINT LOC_PK PRIMARY KEY(DNUMBER, DLOCATION)
);

-- DEPENDENT

CREATE TABLE DEPENDENT(
    ESSN VARCHAR(9),
    DEPENDENT_NAME VARCHAR(15) NOT NULL,
    RELATIONSHIP VARCHAR(20),
    BDATE DATE NOT NULL,
    SEX VARCHAR(1) NOT NULL,

    CONSTRAINT DEPENDENT_PK PRIMARY KEY(ESSN, DEPENDENT_NAME),
    CONSTRAINT DEPENDENT_FK FOREIGN KEY(ESSN) REFERENCES C_EMPLOYEE(SSN) ON DELETE CASCADE
);


-- PROJECT
CREATE TABLE PROJECT(
    PNAME VARCHAR(50) NOT NULL,
    PNUMBER INTEGER,
    PLOCATION VARCHAR(30) NOT NULL,
    DNUM INTEGER,

    CONSTRAINT PROJ_PK PRIMARY KEY(PNUMBER),
    CONSTRAINT PROJ_FK FOREIGN KEY(DNUM) REFERENCES C_DEPARTMENT(DNUMBER)
);

-- WORKS_ON

CREATE TABLE WORKS_ON(
    ESSN VARCHAR(9),
    PNO INTEGER,
    HOURS DECIMAL(6,2),

    CONSTRAINT WORK_PK PRIMARY KEY(ESSN, PNO),
    CONSTRAINT WORK_EMP_FK FOREIGN KEY(ESSN) REFERENCES C_EMPLOYEE(SSN), 
    CONSTRAINT WORK_PROJ_FK FOREIGN KEY(PNO) REFERENCES PROJECT(PNUMBER)
);