-- Q28' not working with
WITH BIGDEPT(DNO) AS (
    SELECT DNO
    FROM C_EMPLOYEE
    GROUP BY DNO
    HAVING COUNT( * ) > 5
)
SELECT DNO, COUNT( * )
FROM EMPLOYEE
WHERE SALARY > 40000
    AND DNO IN BIGDEPT
GROUP BY DNO;

--U6'
SELECT *
FROM EMPLOYEE;

UPDATE EMPLOYEE
SET
    SALARY = (
        CASE WHEN DNO = 30 THEN SALARY + 2000 WHEN DNO = 20 THEN SALARY + 1000 ELSE SALARY + 0
    );

-- Q29  RECURSIVE QUERY not workin
WITH RECURSIVE SUP_EMP (SUPSSN, EMPSSN) AS (
    SELECT SUPER_SSN, SSN
    FROM C_EMPLOYEE UNION
        SELECT E.SSN, S.SUPSSN
        FROM C_EMPLOYEE  E, SUP_EMP  S
        WHERE E.SUPER_SSN = S.EMPSSN
)
SELECT *
FROM SUP_EMP;