--V1 FNAME,LNAME,PNAME,HOURS

CREATE VIEW WORKS_ON_INFO AS
    SELECT FNAME, LNAME, PNAME, HOURS
    FROM C_EMPLOYEE, WORKS_ON, PROJECT
    WHERE SSN = ESSN
        AND PNUMBER = PNO;

SELECT *
FROM WORKS_ON_INFO
WHERE HOURS > 10;

--V2 DEPT INFO, NAME, ENUMS, SALS
CREATE VIEW DEPT_INFO(
    DEPT_NAME, NO_OF_EMPS, TOTAL_SAL
) AS
    SELECT DNAME, COUNT( * ), SUM(SALARY)
    FROM C_DEPARTMENT, C_EMPLOYEE
    WHERE DNO = DNUMBER
    GROUP BY DNAME;

-- DROP VIEW DEPT_INO;

SELECT *
FROM DEPT_INFO;

--QV1 to retrieve the last name and first name of all employees who work on the ‘ProductX’ project, we can utilize the WORKS_ON1 view and specify the query as in QV1:

SELECT FNAME, LNAME
FROM WORKS_ON_INFO
WHERE PNAME = 'ProductX';

--V3 Restrict Tuples
CREATE VIEW DEPT5EMP AS
    SELECT *
    FROM C_EMPLOYEE
    WHERE DNO = 5;

SELECT *
FROM DEPT5EMP;

--Restricting columns
CREATE VIEW BASIC_EMP_DATA AS
    SELECT FNAME, LNAME, ADDRESS
    FROM C_EMPLOYEE;

SELECT *
FROM BASIC_EMP_DATA;