
--SET : union, intersect , except
--MULTISET : union ALL, intersect ALL , except ALL

SELECT DNO
FROM C_EMPLOYEE 
WHERE FNAME LIKE '%a%'

UNION

SELECT DNUMBER
FROM C_DEPARTMENT 
WHERE DNAME LIKE '%e%';

SELECT DNO
FROM C_EMPLOYEE 
WHERE FNAME LIKE '%a%'

UNION ALL

SELECT DNUMBER
FROM C_DEPARTMENT 
WHERE DNAME LIKE '%e%';